# Generated by Django 2.2.3 on 2020-08-04 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='pontos_ataque',
            field=models.IntegerField(default=0, verbose_name='Pontos de Ataque'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='pontos_defesa',
            field=models.IntegerField(default=0, verbose_name='Pontos de Defesa'),
        ),
    ]
