# Generated by Django 2.2.3 on 2020-08-04 22:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20200804_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Game', max_length=255, verbose_name='Nome')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de criação')),
                ('aceite', models.BooleanField(default=False, verbose_name='Aceite')),
                ('iniciado', models.BooleanField(default=False, verbose_name='Iniciado')),
                ('Finalizado', models.BooleanField(default=False, verbose_name='Finalizado')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='system.Categoria', verbose_name='Categoria')),
                ('user_attack', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_attack', to='system.Usuario', verbose_name='Usuário de Ataque')),
                ('user_defense', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_defense', to='system.Usuario', verbose_name='Usuário de Defesa')),
            ],
        ),
    ]
