# Generated by Django 2.2.3 on 2020-08-05 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20200805_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogos',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='jogos',
            name='ganhador',
        ),
        migrations.RemoveField(
            model_name='jogos',
            name='user_attack',
        ),
        migrations.RemoveField(
            model_name='jogos',
            name='user_defense',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='user',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Jogos',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
