# Generated by Django 2.2.3 on 2020-08-04 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_categoria_jogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='fim_jogo',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fim do Jogo'),
        ),
        migrations.AddField(
            model_name='jogo',
            name='inicio_jogo',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inicio do Jogo'),
        ),
    ]
