# Generated by Django 2.2.3 on 2020-08-05 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system', '0003_auto_20200805_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos', models.IntegerField(default=0, verbose_name='Pontos')),
                ('pontos_ataque', models.IntegerField(default=0, verbose_name='Pontos de Ataque')),
                ('pontos_defesa', models.IntegerField(default=0, verbose_name='Pontos de Defesa')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
        migrations.CreateModel(
            name='Jogos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Game', max_length=255, verbose_name='Nome')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de criação')),
                ('pontos', models.IntegerField(default=0, verbose_name='Pontos Recebidos')),
                ('aceite', models.BooleanField(default=False, verbose_name='Aceite')),
                ('iniciado', models.BooleanField(default=False, verbose_name='Iniciado')),
                ('inicio_jogo', models.DateTimeField(blank=True, null=True, verbose_name='Inicio do Game')),
                ('fim_jogo', models.DateTimeField(blank=True, null=True, verbose_name='Fim do Game')),
                ('Finalizado', models.BooleanField(default=False, verbose_name='Finalizado')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='system.Categoria', verbose_name='Categoria')),
                ('ganhador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_ganhador', to='system.Usuario', verbose_name='Ganhador')),
                ('user_attack', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_attack', to='system.Usuario', verbose_name='Usuário de Ataque')),
                ('user_defense', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_defense', to='system.Usuario', verbose_name='Usuário de Defesa')),
            ],
        ),
    ]
