# Generated by Django 2.2.3 on 2020-08-05 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system', '0005_auto_20200805_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogos',
            name='iniciador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='iniciador', to=settings.AUTH_USER_MODEL, verbose_name='Iniciador'),
        ),
    ]
