# Generated by Django 2.2.3 on 2020-08-05 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_jogos_iniciador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jogos',
            old_name='iniciador',
            new_name='desafiado',
        ),
    ]
