# Generated by Django 2.2.3 on 2020-08-24 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_auto_20200805_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogos',
            name='registros_sql',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Pontos Recebidos'),
        ),
        migrations.AlterField(
            model_name='jogos',
            name='desafiado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='iniciador', to=settings.AUTH_USER_MODEL, verbose_name='Desafiado'),
        ),
    ]
